-- 系统内置 Agent 工具的首次安装默认值。
-- Python ToolRegistry 会在服务启动时同步描述、Schema 和运行限制，
-- 但不会覆盖管理员后续调整过的 is_enabled。
INSERT OR IGNORE INTO agent_tools (
    tools_name, display_name, description, owner_user_id, source_kind,
    tool_type, platform, input_schema_json, allowed_roots_json,
    validation_status, is_enabled, requires_confirmation, risk_level,
    timeout_seconds, max_output_bytes, created_at, updated_at
) VALUES
('get_current_time', '获取当前时间', '获取当前服务器本地时间。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 5, 4096, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_hostname', '获取主机名', '获取当前服务器主机名。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 5, 4096, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_current_user', '获取当前用户', '获取运行后端服务的系统用户。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 5, 4096, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_os_info', '获取系统信息', '获取操作系统和架构信息。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_python_runtime_info', '获取 Python 运行环境', '获取 Python 解释器运行信息。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_system_metrics', '获取系统资源指标', '获取 CPU、内存和磁盘基础指标。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('list_directory', '列出目录', '列出目录中的文件和子目录。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('file_stat', '查看文件信息', '查看路径元数据。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('find_files', '查找文件', '按名称通配符查找路径。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 15, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_disk_usage', '查看磁盘空间', '查看路径所在卷的空间。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_process_list', '获取进程列表', '获取有限进程摘要。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_process_detail', '获取进程详情', '按 PID 获取进程详情。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('resolve_host', '解析主机地址', '解析主机名对应地址。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('check_tcp_port', '检测 TCP 端口', '检测 TCP 端口是否可连接。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('calculate_file_hash', '计算文件摘要', '计算文件摘要。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 30, 8192, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('compare_files', '比较文件', '通过大小和摘要比较文件。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 60, 8192, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('list_archive', '查看压缩包目录', '查看 ZIP/TAR 条目。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 30, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('read_text_file', '读取文本文件', '读取有限长度文本。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('read_file_head', '读取文件开头', '读取文本文件前 N 行。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('read_file_tail', '读取文件结尾', '读取文本文件后 N 行。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('search_text', '搜索文本', '搜索目录内文本。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 15, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_directory_size', '查看目录大小', '统计目录大小。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 30, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('http_get', 'HTTP GET 请求', '读取受限公网 HTTP 响应。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 15, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ping_host', 'Ping 主机', '使用原始 ICMP 检测主机。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 0, 'medium', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('create_directory', '创建目录', '创建目录。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('copy_path', '复制文件或目录', '复制路径且保留源数据。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('rename_path', '重命名路径', '同父目录重命名路径。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('write_text_file', '写入文本文件', '写入单个文本文件。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('append_text_file', '追加文本', '追加文本内容。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('replace_text_in_file', '替换文件文本', '在单个文件中有限替换。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('create_archive', '创建压缩包', '创建 ZIP/TAR 压缩包。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('extract_archive', '解压文件', '安全解压 ZIP/TAR。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('download_file', '下载文件', '下载受限大小的公网文件。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 130, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('move_path', '移动文件或目录', '移动后源路径消失。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('delete_path', '删除路径', '删除单个路径。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('delete_directory_contents', '清空目录内容', '批量删除目录直接子项。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kill_process', '结束进程', '结束指定进程。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'high', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kill_process_tree', '结束进程树', '结束指定进程树。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'high', 20, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bulk_replace_text', '批量替换文本', '批量替换目录内文本。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('read_file_range', '读取文件行范围', '按起止行读取文本文件片段。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 15, 262144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_directory_snapshot', '获取目录快照', '获取目录条目、修改时间和可选摘要。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 60, 262144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('compare_directory_snapshots', '比较目录快照', '比较两份目录快照的变化。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 262144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('validate_python_syntax', '校验 Python 语法', '使用 AST 校验 Python 文件，不执行代码。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 15, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('validate_json', '校验 JSON', '校验 JSON 文件并返回错误位置。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 15, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inspect_sqlite_schema', '查看 SQLite 结构', '以只读模式查看 SQLite 表、字段、索引和外键。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 30, 262144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('preview_text_patch', '预览文本补丁', '生成文本 unified diff 和短期操作令牌。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 20, 262144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('apply_text_patch', '应用文本补丁', '使用已确认的短期操作令牌应用文本补丁。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 20, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_repository_status', '查看代码仓库状态', '使用纯 Python 比较 Git index 和工作区。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 60, 262144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_file_diff', '比较文本文件差异', '使用 difflib 比较两个文本文件。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 20, 262144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('list_registered_tasks', '列出注册任务', '列出后端预定义的 Python 测试和编译任务。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('run_registered_task', '运行注册任务', '按 task_id 运行后端预定义任务。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 15, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_task_status', '查询任务状态', '查询注册任务状态和有限日志尾部。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('compare_path_names', '比较路径名称集合', '比较文本逐行名称与目录条目名称，返回统计和有限样本。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 120, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
