-- 系统内置 Agent 工具的首次安装默认值。
-- Python ToolRegistry 会在服务启动时同步描述、Schema 和运行限制，
-- 但不会覆盖管理员后续调整过的 is_enabled。
INSERT OR IGNORE INTO agent_tools (
    tools_name, display_name, description, owner_user_id, source_kind,
    tool_type, platform, input_schema_json, allowed_roots_json,
    validation_status, is_enabled, requires_confirmation, risk_level,
    timeout_seconds, max_output_bytes, created_at, updated_at
) VALUES
('get_current_time', '获取当前时间', '获取当前服务器本地时间。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 5, 4096, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_hostname', '获取主机名', '获取当前服务器主机名。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 5, 4096, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_current_user', '获取当前用户', '获取运行后端服务的系统用户。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 5, 4096, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_os_info', '获取系统信息', '获取操作系统和架构信息。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_python_runtime_info', '获取 Python 运行环境', '获取 Python 解释器运行信息。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_system_metrics', '获取系统资源指标', '获取 CPU、内存和磁盘基础指标。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('list_directory', '列出目录', '列出目录中的文件和子目录。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('file_stat', '查看文件信息', '查看路径元数据。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('find_files', '查找文件', '按名称通配符查找路径。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 15, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_disk_usage', '查看磁盘空间', '查看路径所在卷的空间。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_process_list', '获取进程列表', '获取有限进程摘要。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_process_detail', '获取进程详情', '按 PID 获取进程详情。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('resolve_host', '解析主机地址', '解析主机名对应地址。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('check_tcp_port', '检测 TCP 端口', '检测 TCP 端口是否可连接。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('calculate_file_hash', '计算文件摘要', '计算文件摘要。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 30, 8192, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('compare_files', '比较文件', '通过大小和摘要比较文件。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 60, 8192, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('list_archive', '查看压缩包目录', '查看 ZIP/TAR 条目。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'low', 30, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('read_text_file', '读取文本文件', '读取有限长度文本。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('read_file_head', '读取文件开头', '读取文本文件前 N 行。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('read_file_tail', '读取文件结尾', '读取文本文件后 N 行。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('search_text', '搜索文本', '搜索目录内文本。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 15, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('get_directory_size', '查看目录大小', '统计目录大小。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 30, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('http_get', 'HTTP GET 请求', '读取受限公网 HTTP 响应。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 0, 'medium', 15, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ping_host', 'Ping 主机', '使用原始 ICMP 检测主机。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 0, 'medium', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('create_directory', '创建目录', '创建目录。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('copy_path', '复制文件或目录', '复制路径且保留源数据。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('rename_path', '重命名路径', '同父目录重命名路径。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('write_text_file', '写入文本文件', '写入单个文本文件。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('append_text_file', '追加文本', '追加文本内容。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('replace_text_in_file', '替换文件文本', '在单个文件中有限替换。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 10, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('create_archive', '创建压缩包', '创建 ZIP/TAR 压缩包。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('extract_archive', '解压文件', '安全解压 ZIP/TAR。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('download_file', '下载文件', '下载受限大小的公网文件。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 1, 1, 'medium', 130, 16384, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('move_path', '移动文件或目录', '移动后源路径消失。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('delete_path', '删除路径', '删除单个路径。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('delete_directory_contents', '清空目录内容', '批量删除目录直接子项。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kill_process', '结束进程', '结束指定进程。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 1, 'high', 10, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kill_process_tree', '结束进程树', '结束指定进程树。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 1, 'high', 20, 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('bulk_replace_text', '批量替换文本', '批量替换目录内文本。', NULL, 'system', 'python_builtin', 'all', '{}', '["*"]', 'valid', 0, 1, 'high', 120, 65536, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
